import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import { DatabaseSync } from 'node:sqlite';
import { compile } from './compiler.mjs';
compile(['lib/learning.ts','--bundle','--format=esm','--platform=node','--outfile=.sites-runtime/learning-test.mjs']);
compile(['worker/app.ts','--bundle','--format=esm','--platform=node','--loader:.html=text','--alias:cloudflare:workers=./scripts/local-env.ts','--outfile=.sites-runtime/worker-test.mjs']);
const {seed,ancestry,contextFor}=await import('../.sites-runtime/learning-test.mjs');
const state=seed();state.branches.push({...state.branches[2],id:'unrelated',parentId:'transformers',title:'DO_NOT_INCLUDE_SIBLING',messages:[{id:'private-sibling',role:'user',content:'DO_NOT_INCLUDE_SIBLING'}]});
assert.deepEqual(ancestry(state.branches,'dot-product').map(b=>b.id),['transformers','attention','dot-product']);
assert(!JSON.stringify(contextFor(state.branches,'dot-product')).includes('DO_NOT_INCLUDE_SIBLING'));
assert(JSON.stringify(contextFor(state.branches,'dot-product')).includes('A dot product compares'));
const focused=structuredClone(state.branches);focused[1].sourceSnapshot='UNRELATED_BEGINNING_MARKER '+('DISTANT_TEXT '.repeat(1200))+'attention LOCAL_CONTEXT '+('AFTER_TEXT '.repeat(1200));const focusedContext=JSON.stringify(contextFor(focused,'attention'));
assert(focusedContext.includes('LOCAL_CONTEXT'));assert(!focusedContext.includes('UNRELATED_BEGINNING_MARKER'));
assert(focusedContext.length<40000);
const db=new DatabaseSync(':memory:');db.exec(await fs.readFile('drizzle/0000_learning_workspaces.sql','utf8'));
globalThis.__branchroomLocalEnv={DB:{prepare(sql){let args=[];return{bind(...values){args=values;return this;},async first(){return db.prepare(sql).get(...args)||null;},async run(){const r=db.prepare(sql).run(...args);return{meta:{changes:Number(r.changes)}};}}}}};
const worker=(await import('../.sites-runtime/worker-test.mjs')).default;
function request(path,method='GET',data,user='learner-a') {return new Request('https://branchroom.test'+path,{method,headers:{'Content-Type':'application/json',...(user?{'oai-authenticated-user-id':user,'oai-authenticated-user-email':user+'@test.invalid'}:{})},...(data?{body:JSON.stringify(data)}:{})});}
assert.equal((await worker.fetch(request('/api/workspace','GET',null,null),{})).status,401);
assert.equal((await worker.fetch(request('/api/provider','POST',{action:'chat'},null),{})).status,401);
let saved=await worker.fetch(request('/api/workspace','PUT',{state,revision:0}),{});assert.equal(saved.status,200);assert.equal((await saved.json()).revision,1);
const read=await (await worker.fetch(request('/api/workspace'),{})).json();assert.equal(read.state.branches.length,4);assert.equal(read.revision,1);
const other=await(await worker.fetch(request('/api/workspace','GET',null,'learner-b'),{})).json();assert.equal(other.state,null);
assert.equal((await worker.fetch(request('/api/workspace','PUT',{state,revision:0}),{})).status,409);
assert.equal((await worker.fetch(request('/api/workspace','PUT',{state,revision:1}),{})).status,200);
const cyclic=structuredClone(state);cyclic.branches[0].parentId='dot-product';assert.equal((await worker.fetch(request('/api/workspace','PUT',{state:cyclic,revision:2}),{})).status,400);
assert.equal((await worker.fetch(request('/api/provider','POST',{action:'chat',region:'global',model:'test',messages:[]}),{})).status,400);
let sent;const actualFetch=globalThis.fetch;
globalThis.fetch=async(url,options)=>{sent={url,options};return new Response('data: {"choices":[{"delta":{"content":"test answer"}}]}\n\ndata: [DONE]\n\n',{headers:{'Content-Type':'text/event-stream'}});};
const streamed=await worker.fetch(request('/api/provider','POST',{action:'chat',key:'test-only-key',region:'global',model:'test-model',messages:[{role:'user',content:'hello'}]}),{});
assert.equal(streamed.status,200);assert((await streamed.text()).includes('test answer'));assert.equal(sent.url,'https://api.moonshot.ai/v1/chat/completions');assert.equal(JSON.parse(sent.options.body).model,'test-model');assert.equal(JSON.parse(sent.options.body).stream,true);
// Modal uses the exact supplied destination and must not inherit a Moonshot secret.
globalThis.__branchroomLocalEnv.KIMI_API_KEY='moonshot-secret-not-for-modal';
const modalInput={action:'chat',region:'modal',model:'self-hosted-model',messages:[{role:'user',content:'hello'}]};
sent=null;
const modalResponse=await worker.fetch(request('/api/provider','POST',modalInput),{});
assert.equal(modalResponse.status,400);assert.equal(sent,null);
await worker.fetch(request('/api/provider','POST',{...modalInput,key:'wk-test.ws-test'}),{});
assert.equal(sent.url,'https://masumthakkar41--ep-kimi-k3-server.us-west.modal.direct/v1/chat/completions');
assert.equal(sent.options.headers.Authorization,'Bearer wk-test.ws-test');assert.equal(sent.options.redirect,'error');
assert.equal(JSON.parse(sent.options.body).model,'self-hosted-model');
assert.equal(JSON.parse(sent.options.body).max_tokens,1400);
await worker.fetch(request('/api/provider','POST',{...modalInput,key:'modal-test-key'}),{});
assert.equal(sent.options.headers.Authorization,'Bearer modal-test-key');
globalThis.fetch=async(url,options)=>{sent={url,options};return Response.json({data:[{id:'my-served-kimi'}]});};
const models=await worker.fetch(request('/api/provider','POST',{action:'models',region:'modal',key:'wk-test.ws-test'}),{});
assert.deepEqual((await models.json()).models,['my-served-kimi']);
assert.equal(sent.url,'https://masumthakkar41--ep-kimi-k3-server.us-west.modal.direct/v1/models');
globalThis.fetch=async()=>new Response('missing',{status:404});
const unavailable=await worker.fetch(request('/api/provider','POST',{action:'models',region:'modal',key:'wk-test.ws-test'}),{});
assert.equal(unavailable.status,400);assert.match((await unavailable.json()).error,/manually/);
globalThis.fetch=actualFetch;db.close();
console.log('PASS: focused branch context, sibling isolation, saved state, account isolation, stale-write protection, cycle rejection, authentication, missing-key handling, and streaming proxy contract.');
